<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Shared\EcoRuteando.Shared\EcoRuteando.Shared.csproj" />
		<ProjectReference Include="..\EcoRuteando.Modules.Mobility.Application\EcoRuteando.Modules.Mobility.Application.csproj" />
		<ProjectReference Include="..\EcoRuteando.Modules.Mobility.Domain\EcoRuteando.Modules.Mobility.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0" />

		<PackageReference Include="Npgsql" Version="9.0.0" />

		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />

		<!-- Plugin PostGIS: soporte para columnas GEOGRAPHY (POINT/LINESTRING) -->
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" Version="9.0.0" />

	</ItemGroup>

</Project>