<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

 

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\EcoRuteando.Shared\EcoRuteando.Shared.csproj" />
    <ProjectReference Include="..\EcoRuteando.Modules.Security.Domain\EcoRuteando.Modules.Security.Domain.csproj" />
  </ItemGroup>

 

  <ItemGroup>
    <Folder Include="Roles\Shared\Validators\" />
    <Folder Include="Users\Commands\NewFolder\" />
  </ItemGroup>

</Project>
